
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up the C compiler
      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build the application
      - name: Build Inventory Manager
        run: gcc -o inventory_manager inventory_manager.c

      # Step 4: Run Tests (if test cases are added)
      - name: Run Tests
        run: |
          echo "Running automated tests..."
          ./inventory_manager < input_test.txt > output_test.txt
          diff -q expected_output.txt output_test.txt || (echo "Test failed!" && exit 1)

      # Step 5: Clean up build artifacts
      - name: Clean Up
        run: rm -f inventory_manager output_test.txt
