name: C CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up the C compiler
      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build the application
      - name: Build Inventory Manager
        run: gcc -o Team6/inventory_manager Team6/inventory_manager.c

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          echo "Running automated tests..."
          ./Team6/inventory_manager < Team6/input_test.txt > Team6/output_test.txt
          diff -q Team6/expected_output.txt Team6/output_test.txt || (echo "Test failed!" && exit 1)

      # Step 5: Clean up build artifacts
      - name: Clean Up
        run: rm -f Team6/inventory_manager Team6/output_test.txt
